plugins {
    id "com.android.application"
}

android {
    namespace "com.maachan.novelstudy"
    compileSdk 35

    defaultConfig {
        applicationId "com.maachan.novelstudy"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "1.1.0"
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.12.1"
}
